apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: awesomeapps
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJkb2NrZXJhY3IxNC5henVyZWNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJaRzlqYTJWeVlXTnlNVFE2UVhvMFVUbDJkRXM1VUdKVU0zbFBiekY0YVZoSlp6bFVMM2x2Wlcwckt6VTJNRkEyVmk5SVEyNTBLMEZEVWtKRVRVOTJSUT09IgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJzYW1wbGV5YXNoLmF6dXJlY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImMyRnRjR3hsZVdGemFEb3paVWhDTlRjMVZTOWhjWFZXTmxFM1lqbG5TMXBvYm5vMU1saHRkQ3Q2WldOeFNEbHRiR3MzY20wclFVTlNSR3RhTjNOVyIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0K
type: kubernetes.io/dockerconfigjson