name: Build maven
on: push
jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - uses: docker/login-action@v3.1.0
      with:
        registry: githubaction.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{  secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags: githubaction.azurecr.io/myactionrepo:latest
     
        
